# Generated by Django 3.1.2 on 2020-11-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebill', '0002_auto_20201107_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ebill.cliente', verbose_name='<django.db.models.query_utils.DeferredAttribute object at 0x7fe3d75f26d0>'),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebill.factura', verbose_name='Numero de factura: <django.db.models.query_utils.DeferredAttribute object at 0x7fe3d75f2ac0>'),
        ),
    ]
