# Generated by Django 3.1.2 on 2020-11-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebill', '0003_auto_20201107_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ebill.cliente'),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebill.factura'),
        ),
    ]
